[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "ibm.ctg"
version = "0.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IBM", "CICS", "CTG", "Mainframe"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ibm.ctg"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ibm.ctg-native"
version = "0.1.0"
path = "../native/build/libs/ibm.ctg-native-0.1.0.jar"

[[platform.java17.dependency]]
groupId = "wso2"
artifactId = "ctgclient"
version = "9.3"
path = "./lib/ctgclient-9.3.jar"
scope = "provided"

[[platform.java17.dependency]]
groupId = "wso2"
artifactId = "ccf2"
version = "9.3"
path = "./lib/ccf2-9.3.jar"
scope = "provided"

[[platform.java17.dependency]]
groupId = "wso2"
artifactId = "cicsjee"
version = "9.3"
path = "./lib/cicsjee-9.3.jar"
scope = "provided"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.18.0"
path = "./lib/jackson-databind-2.18.0.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.18.0"
path = "./lib/jackson-core-2.18.0.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.18.0"
path = "./lib/jackson-annotations-2.18.0.jar"

[[platform.java17.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.17.0"
path = "./lib/commons-io-2.17.0.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents.core5"
artifactId = "httpcore5"
version = "5.3"
path = "./lib/httpcore5-5.3.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents.core5"
artifactId = "httpcore5-h2"
version = "5.3"
path = "./lib/httpcore5-h2-5.3.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents.client5"
artifactId = "httpclient5"
version = "5.4"
path = "./lib/httpclient5-5.4.jar"

[[platform.java17.dependency]]
groupId = "org.apache.geronimo.specs"
artifactId = "geronimo-j2ee-connector_1.6_spec"
version = "1.0"
path = "./lib/geronimo-j2ee-connector_1.6_spec-1.0.jar"
